### ISSUE TITLE
[Bug] Posting In Catalog Mode, Returns You To Feed

### ISSUE THREAD

**Issue by seniorm0ment** [FChannel0/FChannel-Server#10]
If I go into catalog mode, click on a post, then reply to it, after it replies, it sibmits it and kicks me right out into the feed.

**Comment by FChannel0** [comment]
Implement because of older 4chan functionality before convince was a factor, you type 
>noko
In the options field to return back to your post you made
Now, with this there is a bug when using noko when trying to return to a federated board outside of the instance you are using.

**Comment by FChannel0** [comment]
upon reflection I think I misunderstood your OP. Now I see it as  after you post you should go back to catalog view if you posted from the catalog since currently when you post from catalog view you get redirected to the feed view. 
this is a bug and I will fix it to correctly route.

**Comment by FChannel0** [comment]
this was fixed by knotteye
