### ISSUE TITLE
Board management doesn't work when running on non-standard ports

### ISSUE THREAD

**Issue by knotteye** [FChannel0/FChannel-Server#12]
To reproduce: set config to some non-standard http port (e.g. 3000) then go to localhost:3000/[mod key]
Making the auth request will fail because the post request for /auth (main.go:664) doesn't take the port into account.

Fixing this by adding the port reveals a similar issue that requests based on actor endpoints (like the one in main.go:599) generated from GetActorFromDB don't take ports into account either.

**Comment by FChannel0** [comment]
if you are in a local environment the config should be 
instance:localhost:3000
instancetp:http://
instanceport:3000
for local testing the port has to be in both parts.

production env would look like 
instance:fchan.xyz
instancetp:https://
instanceport:3000

with port not added to the instance

**Comment by knotteye** [comment]
Oh, okay. Thank you!
