### ISSUE TITLE
Invalid Captcha sends you to a different page

### ISSUE THREAD

**Issue by seth-scherer** [FChannel0/FChannel-Server#14]
This makes you lose the entirety of your message that you typed out. Having it give a warning message, rather than redirecting a new page would probably be better.

**Comment by FChannel0** [comment]
Yes, this could better be implemented for better user friendliness. For the time being, if you input the wrong captcha if you hit the browser back button and then refresh the page your message will still be there to input the new captcha. This is only a temporary solution and better error handling should be implemented.
