### ISSUE TITLE
[bug] Tripcode algorithm is incorrect 

### ISSUE THREAD

**Issue by 153** [FChannel0/FChannel-Server#17]
Tripcode formula is standard for 15+ years on thousands of websites.
For more secure tripcode, use "secure tripcode" (private encryption method with salt) 

the idea of a tripcode is that it's easily carried to most any other anonymous messageboard,
not that it's going to be your identity for a long long time ... 

As far as secure tripcodes go, the requirements are simply to select a hashing technique, which is unique to the server, that can be generated by any method of one's choosing, as long as it's consistent and difficult to break. Easiest way is a complex checksum with a salt 

`name #insecure`
`name ##secure` 

bonus tripcode settings that may be worth visiting : 
- "troll mode", shows the tripcode user's password as plaintext 
- PGPcodes --  signature + pubkey are "the entity" . 
  - PGP people can encrypt, decrypt, sign natively from their client 
- "federated tripcode" is also an activitypub user, local to the server, who can be blocked or followed, retweeted 
- [tripphases](http://worrydream.com/tripphrase/)

**Comment by the-sageman** [comment]
> Tripcode formula is standard for 15+ years on thousands of websites.

What relevance does that have? In a few years that algorithm will get obsoleted by better hardware, you can already see people cracking tripcodes with ease like in this 4chan /qa/ thread: https://boards.4channel.org/qa/thread/4616204
I say that we remove the option for insecure tripcodes and go all the way in secure tripcodes. I believe that a tripcode should stay on the server if there will be secure tripcodes, since then the salt would be pointless if it gets shared around nodes. On another note, I think that classic tripcodes should also be removed for that reason since the tripcode will not stay unique across nodes and again, it would be easy to impersonate someone, unlike my secure tripcode, which would be valid on one node only.

> PGPcodes -- signature + pubkey are "the entity" . 

This sounds like the most viable option, however, PGP signatures would double the size of a post, so I'm not sure about that. To be fair, images take up most of the space, so who cares?

> "federated tripcode" is also an activitypub user, local to the server, who can be blocked or followed, retweeted

So like filters for names? I say that we should also implement filters for text too, if the admin desires to block certain content from some nodes, but keep quality discussions up, then he could implement a filter. I say that it shouldn't be too far off from the 4chanX filter format.

> "troll mode", shows the tripcode user's password as plaintext
> tripphases

big lol

**Comment by FChannel0** [comment]
I implemented a revision of the trip code from before to be more `standard` https://github.com/FChannel0/FChannel-Server/commit/a122d62f78e5f1fd66efc28994809d720a2841ab
There is secure tripcodes now and instances can set their seed in the config file under `instanceseed:`

It can be expanded and corrected as needed. From looking at other algorithms there are a lot of variance between them. I just went with what was simplest atm.

**Comment by 153** [comment]
> What relevance does that have? In a few years that algorithm will get obsoleted by better hardware, you can already see people cracking tripcodes with ease like in this 4chan /qa/ thread: https://boards.4channel.org/qa/thread/4616204

Some of these appear to be leaked (the secure tripcodes; not possible to crack them locally because they have a secret hash) while others can easily be found via brute force or dictionary attacks.  I don't know your experience with cryptography, but no hash algorithm will save you from brute force or dictionary attacks. Keep in mind that nothing fakes a malicious admin from spoofing tripcodes or logging tripcode passwords. An insecure tripcode is not intended to be especially secure. 

Do you really think #TRIPCODE was cracked, or #11111111  due to a weak algorithm? I don't think so. 
tripcode vs Secure tripcode:
tripcode has a public hashing method which is shared between sites.
Secure tripcode has private salt or hashing methods, known only to a site admin.

**Comment by 153** [comment]
> I implemented a revision of the trip code from before to be more 'standard' [a122d62](https://github.com/FChannel0/FChannel-Server/commit/a122d62f78e5f1fd66efc28994809d720a2841ab)
> There is secure tripcodes now and instances can set their seed in the config file under `instanceseed:`
> 
> It can be expanded and corrected as needed. From looking at other algorithms there are a lot of variance between them. I just went with what was simplest atm.

compatible license golang tripcode: 
https://github.com/aquilax/tripcode 

There are some minor differences in how tripcode algos handle edge cases, but 95% or 99% compatibility is nice , even if it's not 100%

**Comment by the-sageman** [comment]
> An insecure tripcode is not intended to be especially secure.

So a regular tripcode is not intended to be safe, just a commonly available algorithm that you can share across sites. The reason I don't really like this approach is that a tripcode is supposed to prove that you are what you say you are, not to be cross-platform compatible, and it's not even good at the former. The examples you listed are pretty easy to find out, but then again, you don't get leaks like these for secure tripcodes, just look at how many regular tripcodes are there in that thread compared to secure tripcodes, which definitely got leaked by somebody like you pointed out. Secure tripcodes are impossible to break for now.

> I don't know your experience with cryptography, but no hash algorithm will save you from brute force or dictionary attacks. 

Obviously no cryptographic measure is going to hold up against time, the only question that there is is how long they will last. It's pretty obvious that regular tripcodes will become even less secure to use in the coming years, but salts, peppers, updated hash algorithms (and passwords!) give crackers an awful lot more of time for cracking.

> Keep in mind that nothing fakes a malicious admin from spoofing tripcodes or logging tripcode passwords.

Fair point, but then we might as well remove the entire tripcode funcionality if we want to prevent passwords to be leaked. Credentials get leaked all the time, and decentralizing the system does not help.
