### ISSUE TITLE
[bug]  Following /pen/ crashed my fchannel

### ISSUE THREAD

**Issue by 153** [FChannel0/FChannel-Server#21]
Steps to reproduce: 
- create /pen
- go to my /pen board
- follow https://fchan.xyz/pen 
- go back
- click "catalog" 
 
When I rebooted and clicked "catalog" again, things worked out fine. 

https://bbs.killthepresident.club/static/log.txt <-- log file

**Comment by FChannel0** [comment]
fixed the runtime error: invalid memory address or nil pointer dereference here https://github.com/FChannel0/FChannel-Server/commit/d8ec39ca028dfed3e2c1ba0193c6fde977ae22b5
