### ISSUE TITLE
Following and unsubscribing bugs in v0.0.10

### ISSUE THREAD

**Issue by anomalous69** [FChannel0/FChannel-Server#43]
I've noticed two bugs that are probably related, following only working one-way, and follower entries not being removed.
Bug 1: If actor1 follows actor2 it works fine, but if actor2 follows actor1 back then they don't show up in actor1's followers, if both were to unsubscribe and actor2 goes first now actor1 is unable to follow back.

Bug 2: If actor1 isn't following actor2 then every time actor2 follows or unfollows duplicate entries are created in actor1's followers.
If actor1 follows actor2 back and actor2 unfollows actor1 then unfollowing works correctly and the entries get removed.
This also occurs with the root actor.
<img alt="duplicate root follower" src="https://user-images.githubusercontent.com/81135357/126035028-09d1f59c-07e9-4e94-9de8-dce7b614944c.png">

I've looked around some of the instances and seen that this has already happened with Usagi (https://fchan.xyz/prog/followers) and CyberiaChan (https://0x00000000.xyz/b/followers)
Also Fedorachan/prog/ is apparently following Usagi/prog/ but they don't show up in Usagi's followers

**Comment by FChannel0** [comment]
ugh this is a nasty bug. thank you for reporting. hopefully will be fixed today before too much of a mess is made. reset master to v0.0.9
this is what you get for saying fuck it well do it live.

**Comment by FChannel0** [comment]
found the bug. i mixed up Following and Followers  in one of the requests and it caused everything to go haywire. fix will be pushed soon, i want to make a few other minor changes.

**Comment by FChannel0** [comment]
Ok, this "should" be fixed. thank you for bringing this to my attention, this could have caused issues if unnoticed for too long. If another issue with following comes up, please let me know. There are some tweaks I need to do for better edge cases when following.
