### ISSUE TITLE
Adjust Repo Name To Be Distinctive

### ISSUE THREAD

**Issue by seniorm0ment** [FChannel0/FChannel-Server#5]
It would be more appropriate for the repository name to be labeled fchannel-server or something instead of server.

**Comment by aschrijver** [comment]
Agree. Also I'd love to add this project to the [AP Watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps), but then also a description should be present. I'll watch this issue and'll update accordingly. You can also reach me at [@humanetech@mastodon.social](https://mastodon.social/@humanetech) or on [SocialHub](https://socialhub.activitypub.rocks).

**Comment by FChannel0** [comment]
Thank you for the suggestion, I have changed it to something more descriptive. 
Also expanded the README, I appreciate the structure laid out in your fork.

**Comment by aschrijver** [comment]
Thank you. I have added an entry to the watchlist :)

**Comment by FChannel0** [comment]
Thank you, I appreciate the addition.
